workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

pages:
  tags:
    - pages
  script:
    - mv res/ scripts/ style.css index.html public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "gitlab-pages"
